import { useState, useEffect } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { useMutation, useQueryClient, useQuery } from "@tanstack/react-query";
import { sendEmailToBrand, getContentTemplates, apiRequest } from "@/lib/api";
import { useToast } from "@/hooks/use-toast";
import { Sparkles, RefreshCw } from "lucide-react";
import type { Brand } from "@shared/schema";

interface EmailComposerModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  brand: Brand | null;
}

export function EmailComposerModal({ open, onOpenChange, brand }: EmailComposerModalProps) {
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const [templateType, setTemplateType] = useState<"general" | "followup">("general");
  const [customSubject, setCustomSubject] = useState("");
  const [aiSuggestions, setAiSuggestions] = useState<string[]>([]);
  const [isGeneratingSuggestions, setIsGeneratingSuggestions] = useState(false);
  const [nicheIdeas, setNicheIdeas] = useState<string[]>([]);
  const [customNicheIdea, setCustomNicheIdea] = useState("");
  const [selectedNicheIdea, setSelectedNicheIdea] = useState("");
  const [isGeneratingNicheIdeas, setIsGeneratingNicheIdeas] = useState(false);
  const [generatedContentSection, setGeneratedContentSection] = useState("");
  const [isRegeneratingEmail, setIsRegeneratingEmail] = useState(false);
  const [showAdvancedOptions, setShowAdvancedOptions] = useState(false);
  const [selectedVideoLink, setSelectedVideoLink] = useState("");
  const [recipientEmail, setRecipientEmail] = useState("");
  const [editedEmailBody, setEditedEmailBody] = useState("");
  const [selectedNotionVideoId, setSelectedNotionVideoId] = useState<string>("auto");

  // Query synced Notion videos
  const { data: notionVideos = [] } = useQuery<any[]>({
    queryKey: ["/api/integrations/notion/videos"],
    queryFn: async () => {
      const res = await fetch("/api/integrations/notion/videos", { credentials: "include" });
      if (!res.ok) return [];
      return res.json();
    },
    enabled: open,
  });

  // Convert HTML generated by preview to editable plain text
  const htmlToText = (html: string) => {
    if (!html) return "";
    return html
      .replace(/<p>/g, "")
      .replace(/<\/p>/g, "\n\n")
      .replace(/<br\s*\/?>/g, "\n")
      .replace(/<strong>/g, "")
      .replace(/<\/strong>/g, "")
      .replace(/<a[^>]* href="([^"]*)"[^>]*>.*?<\/a>/g, "$1") // Extract raw URL
      .replace(/<[^>]*>/g, "") // Strip any other tags
      .replace(/\n{3,}/g, "\n\n") // Normalize empty lines
      .trim();
  };

  const textToHtml = (text: string) => {
    if (!text) return "";
    return text
      .split('\n\n')
      .map(p => {
        const clean = p.trim().replace(/\n/g, '<br/>');
        return `<p>${clean}</p>`;
      })
      .join('');
  };
  
  const { data: contentTemplates = [] } = useQuery({
    queryKey: ["/api/content-templates"],
    queryFn: () => import("@/lib/api").then(m => m.getContentTemplatesTyped()),
    enabled: open && !!brand,
  });

  const sendEmailMutation = useMutation({
    mutationFn: sendEmailToBrand,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/brands"] });
      queryClient.invalidateQueries({ queryKey: ["/api/dashboard/stats"] });
      toast({
        title: "Success",
        description: "Email sent successfully",
      });
      onOpenChange(false);
    },
    onError: (error: any) => {
      toast({
        title: "Error",
        description: error.message || "Failed to send email",
        variant: "destructive",
      });
    },
  });

  const generateNicheIdeas = async (suggestion?: string) => {
    if (!brand) return;
    
    setIsGeneratingNicheIdeas(true);
    try {
      const response = await apiRequest("POST", "/api/ai/generate-niche-ideas", {
        niche: brand.nicho,
        brandName: brand.marca,
        customSuggestion: suggestion || customNicheIdea || undefined
      });
      
      const data = await response.json();
      setNicheIdeas(data.ideas || []);
      toast({
        title: "Success",
        description: suggestion ? "AI ideas generated based on your suggestion!" : "AI niche ideas generated!",
      });
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to generate niche ideas. Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsGeneratingNicheIdeas(false);
    }
  };

  const regenerateEmailWithIdea = async (idea: string) => {
    if (!brand) return;
    
    setIsRegeneratingEmail(true);
    try {
      const response = await apiRequest("POST", "/api/ai/regenerate-email", {
        brandName: brand.marca,
        industry: brand.nicho,
        nicheIdea: idea,
        selectedVideoLink: selectedVideoLink || undefined
      });
      
      const data = await response.json();
      setGeneratedContentSection(data.content);
      toast({
        title: "Success",
        description: "Content section updated with your idea!",
      });
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to regenerate content. Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsRegeneratingEmail(false);
    }
  };

  const handleCustomIdeaSubmit = () => {
    if (!customNicheIdea.trim()) {
      toast({
        title: "Error",
        description: "Please write your idea first",
        variant: "destructive",
      });
      return;
    }
    setSelectedNicheIdea(customNicheIdea);
    regenerateEmailWithIdea(customNicheIdea);
  };

  const generatePreview = () => {
    if (!brand) return "";

    // Find selected or best matching Notion video
    let notionVid: any = null;
    if (selectedNotionVideoId && selectedNotionVideoId !== "auto") {
      notionVid = notionVideos.find((v: any) => v.notionPageId === selectedNotionVideoId || v.id === selectedNotionVideoId);
    } else if (notionVideos.length > 0) {
      const brandNicheLower = (brand.nicho || "").toLowerCase();
      notionVid = notionVideos.find((v: any) => 
        (v.nicho && v.nicho.toLowerCase().includes(brandNicheLower)) ||
        v.title.toLowerCase().includes(brandNicheLower)
      ) || notionVideos[0];
    }

    // Get video link and views from content template fallback
    const contentTemplate = contentTemplates.find(
      (t: any) => t.nicho.toLowerCase() === brand.nicho.toLowerCase()
    );
    
    const videoLink = selectedVideoLink && selectedVideoLink !== "none" ? selectedVideoLink : (contentTemplate?.videoLinks?.[0] || "");
    
    const videoViews = (() => {
      if (!videoLink || videoLink === "none") return "";
      const template = contentTemplates.find(
        (t: any) => t.nicho.toLowerCase() === brand.nicho.toLowerCase()
      );
      if (!template?.videoLinks) return "";
      const videoIndex = template.videoLinks.findIndex((link: string) => link === videoLink);
      if (videoIndex >= 0 && template.videoViews && template.videoViews[videoIndex]) {
        return template.videoViews[videoIndex];
      }
      return template.views || "";
    })();

    // Build Notion Video proposal section
    let notionVideoSection = "";
    if (notionVid) {
      const dateStr = notionVid.targetDate 
        ? new Date(notionVid.targetDate).toLocaleDateString("es-ES", { day: "numeric", month: "long" }) 
        : "próximamente";

      notionVideoSection = `<p>Actualmente tenemos planificado en nuestro calendario de contenidos el próximo vídeo titulado <strong>"${notionVid.title}"</strong> (con fecha estimada de publicación para el <strong>${dateStr}</strong>). Creemos que <strong>${brand.marca}</strong> encajaría perfectamente como patrocinador oficial dentro de este contenido.</p>`;
    } else if (customNicheIdea || selectedNicheIdea) {
      const ideaStr = customNicheIdea || selectedNicheIdea;
      notionVideoSection = `<p>Para lograr un excelente impacto con vuestro producto, os proponemos la siguiente idea de integración de contenido: <strong>"${ideaStr}"</strong>.</p>`;
    }

    if (templateType === "followup") {
      const videoDetail = notionVid ? ` para el vídeo "${notionVid.title}"` : "";
      return `
        <p>Hola equipo de ${brand.marca},</p>
        <p>Soy Carlos Saca de Saca Tech (@saca.technology).</p>
        <p>Quería hacer un seguimiento de nuestro mensaje anterior referente a la oportunidad de colaboración${videoDetail}. Seguimos muy interesados en mostrar vuestros productos a nuestra audiencia.</p>
        <p>¿Tendríais disponibilidad para una breve llamada o intercambio de correos esta semana para concretar los detalles?</p>
        <p>Quedo a vuestra disposición.</p>
        <p>Un cordial saludo,<br><strong>Carlos Saca</strong><br>Saca Tech<br>@saca.technology</p>
      `;
    }

    return `
      <p>Hola equipo de ${brand.marca},</p>
      <p>Soy Carlos Saca de Saca Tech (@saca.technology). Publicamos contenido sobre tecnología e innovación en Instagram, TikTok y YouTube.</p>
      ${brand.campania && brand.campania.toLowerCase() !== "general" ? 
        `<p>En relación a la campaña: <strong>${brand.campania}</strong>, nos encantaría colaborar con vosotros durante este periodo.</p>` : ''}
      <p>Colaboramos con marcas destacadas en el sector, consiguiendo gran alcance y engagement con nuestra audiencia.</p>
      ${notionVideoSection}
      ${videoLink ? `<p>Podéis ver un ejemplo de nuestro formato e integración de contenidos en este vídeo previo: <a href="${videoLink}" target="_blank">${videoLink}</a>${videoViews ? ` (${videoViews})` : ''}.</p>` : ''}
      <p>Quedo a vuestra disposición para comentar los detalles de esta colaboración.</p>
      <p>Un cordial saludo,<br><strong>Carlos Saca</strong><br>Saca Tech<br>@saca.technology</p>
    `;
  };

  const handleSendEmail = () => {
    if (!brand) return;
    
    const emailData: any = {
      brandId: brand.id,
      templateType,
      htmlOverride: textToHtml(editedEmailBody), // Always use edited plain text converted to HTML
      subjectOverride: subject,
      to: recipientEmail,
    };
    
    // Include niche idea if used
    if (selectedNicheIdea || customNicheIdea) {
      emailData.nicheIdeaUsed = selectedNicheIdea || customNicheIdea;
    }
    
    sendEmailMutation.mutate(emailData);
  };

  const generateSubjectSuggestions = async () => {
    if (!brand) return;
    
    setIsGeneratingSuggestions(true);
    try {
      const response = await apiRequest("POST", "/api/ai/generate-subjects", {
        brandName: brand.marca,
        purpose: templateType === "followup" ? "follow-up email" : "brand collaboration outreach",
        count: 3
      });
      
      const data = await response.json();
      setAiSuggestions(data.subjects || []);
      toast({
        title: "Success",
        description: "AI subject suggestions generated!",
      });
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to generate subject suggestions. Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsGeneratingSuggestions(false);
    }
  };

  // Check for pre-selected Notion video from NotionVideosModal
  useEffect(() => {
    if (open) {
      const stored = sessionStorage.getItem("selectedNotionVideo");
      if (stored) {
        try {
          const parsed = JSON.parse(stored);
          if (parsed && parsed.notionPageId) {
            setSelectedNotionVideoId(parsed.notionPageId);
            setCustomNicheIdea(`Integración en vídeo sobre "${parsed.title}"`);
          }
        } catch (e) {}
        sessionStorage.removeItem("selectedNotionVideo");
      }
    }
  }, [open]);

  // Reset all states when brand or template changes
  useEffect(() => {
    setCustomSubject("");
    setAiSuggestions([]);
    setNicheIdeas([]);
    setSelectedNicheIdea("");
    setGeneratedContentSection("");
    setSelectedVideoLink("");
    setCustomNicheIdea("");
    setShowAdvancedOptions(false);
    if (brand) {
      setRecipientEmail(brand.correo || "");
    }
  }, [brand, templateType]);

  // Pre-fill with template data when brand and templates are available
  useEffect(() => {
    if (brand && contentTemplates.length > 0) {
      const brandContentTemplate = contentTemplates.find(
        (t: any) => t.nicho.toLowerCase() === brand.nicho.toLowerCase()
      );
      if (brandContentTemplate) {
        // Pre-fill the idea field if available
        if (brandContentTemplate.idea) {
          setCustomNicheIdea(brandContentTemplate.idea);
        }
        // Set first video link as default if available
        if (brandContentTemplate.videoLinks && brandContentTemplate.videoLinks.length > 0) {
          setSelectedVideoLink(brandContentTemplate.videoLinks[0]);
        }
      }
    }
  }, [brand?.nicho, contentTemplates.length]); // Only depend on brand niche and template count

  // Pre-fill email recipient
  useEffect(() => {
    if (brand) {
      setRecipientEmail(brand.correo || "");
    }
  }, [brand]);

  // Update plain text editedEmailBody when templates/parameters change
  useEffect(() => {
    if (brand) {
      setEditedEmailBody(htmlToText(generatePreview()));
    }
  }, [brand, templateType, selectedVideoLink, customNicheIdea, selectedNicheIdea, contentTemplates]);


  if (!brand) return null;

  const defaultSubject = templateType === "followup" 
    ? `Follow-up: Collaboration — ${brand.marca}`
    : `Collaboration ${brand.campania || ""} — ${brand.marca}`;
    
  const subject = customSubject || defaultSubject;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-4xl max-h-[90vh] overflow-auto">
        <DialogHeader>
          <DialogTitle>Compose Email</DialogTitle>
          <DialogDescription>
            Send personalized outreach email with AI-generated suggestions
          </DialogDescription>
        </DialogHeader>
        
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {/* Email Form */}
          <div className="space-y-6">
            <div>
              <Label>To</Label>
              <Input
                value={recipientEmail}
                onChange={(e) => setRecipientEmail(e.target.value)}
                placeholder="recipient@example.com"
                data-testid="input-email-to"
              />
            </div>
            
            <div>
              <div className="flex items-center justify-between mb-2">
                <Label>Subject</Label>
                <Button
                  type="button"
                  size="sm"
                  variant="outline"
                  onClick={generateSubjectSuggestions}
                  disabled={isGeneratingSuggestions}
                  className="text-xs"
                  data-testid="button-generate-subjects"
                >
                  <Sparkles className="h-3 w-3 mr-1" />
                  {isGeneratingSuggestions ? "Generating..." : "AI Suggestions"}
                </Button>
              </div>
              <Input
                value={customSubject}
                onChange={(e) => setCustomSubject(e.target.value)}
                placeholder={defaultSubject}
                data-testid="input-email-subject"
              />
              {aiSuggestions.length > 0 && (
                <div className="mt-3 space-y-2">
                  <Label className="text-xs text-muted-foreground">AI Suggestions (click to use):</Label>
                  {aiSuggestions.map((suggestion, index) => (
                    <button
                      key={index}
                      type="button"
                      className="block w-full text-left px-3 py-2 text-xs bg-muted/50 hover:bg-muted rounded border transition-colors"
                      onClick={() => setCustomSubject(suggestion)}
                      data-testid={`suggestion-${index}`}
                    >
                      {suggestion}
                    </button>
                  ))}
                </div>
              )}
            </div>
            
            <div>
              <Label>Template</Label>
              <Select value={templateType} onValueChange={(value: "general" | "followup") => setTemplateType(value)}>
                <SelectTrigger data-testid="select-template-type">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="general">General Collaboration</SelectItem>
                  <SelectItem value="followup">Follow-up</SelectItem>
                </SelectContent>
              </Select>
            </div>
            
            {/* Customization Options for General Template */}
            {templateType === "general" && (
              <div className="space-y-4">
                <Label className="text-base font-medium">Customize Content for {brand.nicho}</Label>
                
                {/* Notion Calendar Video Selector */}
                {notionVideos.length > 0 && (
                  <div className="bg-indigo-50/50 dark:bg-indigo-950/20 p-4 rounded-lg border border-indigo-200/60 dark:border-indigo-900/50 space-y-2">
                    <Label className="text-sm font-semibold flex items-center gap-1.5 text-indigo-700 dark:text-indigo-400">
                      📅 Vídeo del Calendario de Notion a Ofrecer
                      <Badge variant="outline" className="text-[10px] ml-auto border-indigo-300 text-indigo-600">
                        {notionVideos.length} disponibles
                      </Badge>
                    </Label>
                    <Select
                      value={selectedNotionVideoId}
                      onValueChange={(val) => {
                        setSelectedNotionVideoId(val);
                        if (val !== "auto") {
                          const v = notionVideos.find((nv: any) => nv.notionPageId === val || nv.id === val);
                          if (v) {
                            const dateStr = v.targetDate ? new Date(v.targetDate).toLocaleDateString("es-ES", { day: "numeric", month: "short" }) : "Próximamente";
                            setCustomNicheIdea(`Integración en el vídeo "${v.title}" (Previsto: ${dateStr})`);
                            regenerateEmailWithIdea(`Integración en el vídeo "${v.title}" (Previsto: ${dateStr})`);
                          }
                        }
                      }}
                    >
                      <SelectTrigger className="bg-card text-sm">
                        <SelectValue placeholder="Seleccionar vídeo de Notion..." />
                      </SelectTrigger>
                      <SelectContent className="max-h-60">
                        <SelectItem value="auto">✨ Seleccionar automáticamente según nicho ({brand.nicho})</SelectItem>
                        {notionVideos.map((v: any) => {
                          const dateStr = v.targetDate ? new Date(v.targetDate).toLocaleDateString("es-ES", { day: "numeric", month: "short" }) : "Sin fecha";
                          return (
                            <SelectItem key={v.notionPageId || v.id} value={v.notionPageId || v.id}>
                              🎬 {v.title} ({dateStr}) {v.nicho ? `[${v.nicho}]` : ""}
                            </SelectItem>
                          );
                        })}
                      </SelectContent>
                    </Select>
                  </div>
                )}

                {/* Custom Idea Input */}
                <div className="space-y-3 bg-blue-50 dark:bg-blue-900/20 p-4 rounded-lg border border-blue-200 dark:border-blue-800">
                  <Label className="text-sm font-medium">Your Content Idea (Optional)</Label>
                  <Input
                    value={customNicheIdea}
                    onChange={(e) => setCustomNicheIdea(e.target.value)}
                    placeholder="e.g., 'Test waterproof feature in swimming pool'"
                    className="flex-1"
                    data-testid="input-custom-niche-idea"
                  />
                  <div className="flex space-x-2">
                    <Button
                      type="button"
                      onClick={() => generateNicheIdeas(customNicheIdea)}
                      disabled={isGeneratingNicheIdeas || !customNicheIdea.trim()}
                      variant="default"
                      size="sm"
                      data-testid="button-generate-with-suggestion"
                    >
                      <Sparkles className="h-4 w-4 mr-1" />
                      {isGeneratingNicheIdeas ? "Generating..." : "Get Ideas Based on This"}
                    </Button>
                    <Button
                      type="button"
                      onClick={handleCustomIdeaSubmit}
                      disabled={isRegeneratingEmail || !customNicheIdea.trim()}
                      variant="outline"
                      size="sm"
                      data-testid="button-use-custom-idea"
                    >
                      <RefreshCw className="h-4 w-4 mr-1" />
                      {isRegeneratingEmail ? "Generating..." : "Use Directly"}
                    </Button>
                  </div>
                </div>
                
                {/* Existing Content Ideas Selection */}
                {(() => {
                  const contentTemplate = contentTemplates.find(
                    (t: any) => t.nicho.toLowerCase() === brand.nicho.toLowerCase()
                  );
                  
                  // Extract existing ideas from template
                  const existingIdeas: string[] = [];
                  
                  if (contentTemplate?.idea) {
                    const ideaLines = contentTemplate.idea.split('\n').filter(line => line.trim());
                    
                    ideaLines.forEach((line) => {
                      const cleanLine = line.replace(/^•\s*/, '').trim();
                      
                      // Check if this line contains a formatted idea
                      const fullFormatMatch = cleanLine.match(/In order to achieve good reach with your product, I propose the following content idea:\s*["""']\s*([^"""']+?)\s*["""']/i);
                      if (fullFormatMatch) {
                        const extractedIdea = fullFormatMatch[1].trim();
                        if (extractedIdea && !existingIdeas.includes(extractedIdea)) {
                          existingIdeas.push(extractedIdea);
                        }
                      } else {
                        // If not formatted, check if it's a simple idea
                        if (cleanLine && 
                            cleanLine.length < 150 && 
                            cleanLine.length > 3 && // Don't take single letters or too short text
                            !cleanLine.includes('In order to achieve') && 
                            !cleanLine.includes('I want to show you') &&
                            !cleanLine.includes('according to the link') &&
                            !existingIdeas.includes(cleanLine)) {
                          existingIdeas.push(cleanLine);
                        }
                      }
                    });
                    
                    // Also check originalIdea and proposedIdea fields if they exist
                    if (contentTemplate.originalIdea && !existingIdeas.includes(contentTemplate.originalIdea)) {
                      existingIdeas.push(contentTemplate.originalIdea);
                    }
                    if (contentTemplate.proposedIdea && !existingIdeas.includes(contentTemplate.proposedIdea)) {
                      existingIdeas.push(contentTemplate.proposedIdea);
                    }
                  }
                  
                  return existingIdeas.length > 0 && (
                    <div className="space-y-3 bg-purple-50 dark:bg-purple-900/20 p-4 rounded-lg border border-purple-200 dark:border-purple-800">
                      <Label className="text-sm font-medium">Pre-existing Content Ideas</Label>
                      <p className="text-xs text-muted-foreground">Select from ideas already saved for this niche</p>
                      <Select 
                        value={selectedNicheIdea} 
                        onValueChange={(value) => {
                          setSelectedNicheIdea(value === "none" ? "" : value);
                          if (value !== "none") {
                            setCustomNicheIdea(value);
                          }
                        }}
                      >
                        <SelectTrigger data-testid="select-existing-idea">
                          <SelectValue placeholder="Choose a pre-existing idea..." />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="none">No pre-existing idea</SelectItem>
                          {existingIdeas.map((idea: string, index: number) => (
                            <SelectItem key={index} value={idea}>
                              {idea.length > 60 ? `${idea.substring(0, 60)}...` : idea}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                      {selectedNicheIdea && (
                        <p className="text-xs text-muted-foreground bg-white dark:bg-gray-800 p-2 rounded border">
                          Selected idea: {selectedNicheIdea}
                        </p>
                      )}
                    </div>
                  );
                })()}

                {/* Video Link Selection */}
                {(() => {
                  const videoTemplate = contentTemplates.find(
                    (t: any) => t.nicho.toLowerCase() === brand.nicho.toLowerCase()
                  );
                  return videoTemplate && (
                    <div className="space-y-3 bg-green-50 dark:bg-green-900/20 p-4 rounded-lg border border-green-200 dark:border-green-800">
                      <Label className="text-sm font-medium">Reference Video Link</Label>
                      <p className="text-xs text-muted-foreground">Enter or edit the video link to reference in your content idea</p>
                      <Input
                        value={selectedVideoLink}
                        onChange={(e) => setSelectedVideoLink(e.target.value)}
                        placeholder="Reference video link (e.g. https://youtube.com/...)"
                        data-testid="input-video-link"
                      />
                      {videoTemplate.videoLinks && videoTemplate.videoLinks.length > 0 && (
                        <div className="space-y-1.5 mt-2">
                          <Label className="text-[10px] text-muted-foreground">Quick suggestions (click to use):</Label>
                          <div className="flex flex-wrap gap-1.5">
                            {videoTemplate.videoLinks.map((link: string, index: number) => (
                              <button
                                key={index}
                                type="button"
                                className={`text-[10px] border px-2 py-1 rounded truncate max-w-[200px] transition-colors ${
                                  selectedVideoLink === link
                                    ? "bg-green-600 text-white border-green-600"
                                    : "bg-background hover:bg-muted text-foreground border-border"
                                }`}
                                onClick={() => setSelectedVideoLink(link)}
                                title={link}
                              >
                                {link.length > 25 ? `${link.substring(0, 25)}...` : link}
                              </button>
                            ))}
                          </div>
                        </div>
                      )}
                    </div>
                  );
                })()}
                
                {/* AI Generated Ideas */}
                <div>
                  <div className="flex items-center justify-between mb-3">
                    <Label>AI Suggestions</Label>
                    <Button
                      type="button"
                      size="sm"
                      variant="outline"
                      onClick={() => generateNicheIdeas()}
                      disabled={isGeneratingNicheIdeas}
                      className="text-xs"
                      data-testid="button-generate-niche-ideas"
                    >
                      <Sparkles className="h-3 w-3 mr-1" />
                      {isGeneratingNicheIdeas ? "Generating..." : "Get Random Ideas"}
                    </Button>
                  </div>
                  
                  {nicheIdeas.length > 0 && (
                    <div className="space-y-3">
                      {nicheIdeas.map((idea, index) => (
                        <div key={index} className="flex items-center space-x-3">
                          <button
                            type="button"
                            className={`flex-1 text-left p-3 rounded border transition-colors ${
                              selectedNicheIdea === idea 
                                ? "bg-primary/10 border-primary" 
                                : "bg-muted/50 hover:bg-muted border-border"
                            }`}
                            onClick={() => {
                              setSelectedNicheIdea(idea);
                              regenerateEmailWithIdea(idea);
                            }}
                            disabled={isRegeneratingEmail}
                            data-testid={`niche-idea-${index}`}
                          >
                            <div className="text-sm font-medium text-foreground">{`AI Idea ${index + 1}`}</div>
                            <div className="text-xs text-muted-foreground mt-1">{idea}</div>
                          </button>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              </div>
            )}
            
            <div>
              <Label>Variables</Label>
              <div className="space-y-3 bg-muted/50 p-4 rounded-lg">
                <div className="flex justify-between text-sm">
                  <span className="text-muted-foreground">{"{{contacto}}"}</span>
                  <span className="text-foreground">{brand.contacto || "team"}</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-muted-foreground">{"{{marca}}"}</span>
                  <span className="text-foreground">{brand.marca}</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-muted-foreground">{"{{nicho}}"}</span>
                  <Badge variant="secondary">{brand.nicho}</Badge>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-muted-foreground">{"{{campaña}}"}</span>
                  <span className="text-foreground">{brand.campania || "General"}</span>
                </div>
              </div>
            </div>
          </div>
          
          {/* Email Preview */}
          <div className="flex flex-col h-full space-y-2">
            <Label htmlFor="edited-email-body">Email Body (Editable)</Label>
            <Textarea
              id="edited-email-body"
              value={editedEmailBody}
              onChange={(e) => setEditedEmailBody(e.target.value)}
              className="flex-1 min-h-[350px] font-sans text-sm p-4 bg-muted/30 focus:bg-background border rounded-lg resize-y leading-relaxed"
              data-testid="textarea-email-body"
              placeholder="Draft your email here..."
            />
            <p className="text-[10px] text-muted-foreground">
              You can edit the greeting, sign-off, or pitch text directly. Line breaks will be preserved.
            </p>
          </div>
        </div>
        
        <div className="flex items-center justify-between pt-6 border-t border-border">
          <div></div>
          <div className="flex items-center space-x-4">
            <Button
              type="button"
              variant="ghost"
              onClick={() => onOpenChange(false)}
              data-testid="button-cancel-email"
            >
              Cancel
            </Button>
            <Button
              onClick={handleSendEmail}
              disabled={sendEmailMutation.isPending}
              data-testid="button-send-email"
            >
              {sendEmailMutation.isPending ? "Sending..." : "Send Email"}
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
